# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg.proto',
  package='msg',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tmsg.proto\x12\x03msg\"+\n\x07\x41\x63\x63ount\x12\x13\n\x0b\x61\x63\x63ountName\x18\x01 \x02(\t\x12\x0b\n\x03pwd\x18\x02 \x02(\t\"8\n\x0b\x41\x63\x63ountList\x12\r\n\x05index\x18\x01 \x02(\x05\x12\x1a\n\x04list\x18\x02 \x03(\x0b\x32\x0c.msg.Account')
)




_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='msg.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountName', full_name='msg.Account.accountName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwd', full_name='msg.Account.pwd', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=61,
)


_ACCOUNTLIST = _descriptor.Descriptor(
  name='AccountList',
  full_name='msg.AccountList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='msg.AccountList.index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list', full_name='msg.AccountList.list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=119,
)

_ACCOUNTLIST.fields_by_name['list'].message_type = _ACCOUNT
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['AccountList'] = _ACCOUNTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNT,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:msg.Account)
  ))
_sym_db.RegisterMessage(Account)

AccountList = _reflection.GeneratedProtocolMessageType('AccountList', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTLIST,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:msg.AccountList)
  ))
_sym_db.RegisterMessage(AccountList)


# @@protoc_insertion_point(module_scope)
